//
//  Router.swift
//  ZeroHTTP
//
//  Created by Philipp Kotte on 03.07.25.
//

import Foundation
import ZeroErrors

/// A thread-safe router that manages and dispatches requests to registered routes.
public final class Router: @unchecked Sendable {
    /// The shared singleton instance, allowing global access to the router.
    @MainActor public static let shared = Router()
    
    // A private lock to protect concurrent access to the `_routes` array.
    private let lock = NSLock()
    
    // The internal storage for routes. Access must be synchronized.
    private var _routes: [Route] = []

    /// A thread-safe computed property to get the routes.
    public var routes: [Route] {
        lock.lock()
        defer { lock.unlock() }
        return _routes
    }

    /// A private initializer to enforce the singleton pattern.
    private init() {}

    /// Registers all routes from a given controller in a thread-safe manner.
    /// - Parameter controller: The controller whose routes should be registered.
    public func register(controller: Controller) {
        lock.lock()
        defer { lock.unlock() }
        self._routes.append(contentsOf: controller.body)
    }

    /// Handles an incoming request by finding a matching route and executing its handler.
    ///
    /// This method supports both exact path matching and wildcard matching (e.g., "/public/*").
    /// It is thread-safe, creating a local copy of the routes to iterate over.
    ///
    /// - Parameter request: The `HttpRequest` object to handle.
    /// - Returns: An `HttpResponse` generated by the matched route's handler, or a 404 response.
    public func handle(request: HttpRequest) -> HttpResponse {
        // Create a local, thread-safe copy of the routes to iterate over.
        // This minimizes the time the lock is held.
        let currentRoutes = self.routes
        
        for route in currentRoutes {
            // Wildcard matching for paths ending in "*"
            if route.path.hasSuffix("*") {
                let prefix = route.path.dropLast()
                if request.path.hasPrefix(prefix) {
                    return route.handler(request)
                }
            }
            // Exact path matching
            else if route.path == request.path {
                return route.handler(request)
            }
        }
        
        // If no route was matched, return a standard 404 response.
        let body = resourceNotFound
        var headers = HttpHeaders()
        headers["Content-Type"] = "text/html; charset=utf-8"
        
        return HttpResponse(status: .notFound, statusPhrase: "Not Found", headers: headers, body: body.data(using: .utf8))
    }
}
